# Generated by Django 2.2.28 on 2025-03-25 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location_forum', models.URLField()),
                ('rating', models.IntegerField(default=0)),
                ('weather_description', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('saved_locations', jsonfield.fields.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=128)),
                ('max_comments', models.IntegerField(default=0)),
                ('weather_data', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_django.Location')),
            ],
            options={
                'verbose_name_plural': 'Forums',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
                ('slug', models.SlugField()),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_django.Forum')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
