# Generated by Django 2.2.28 on 2025-03-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='locationName',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
