# Generated by Django 2.2.28 on 2025-03-26 21:48

from django.contrib.postgres.operations import UnaccentExtension, TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_django', '0001_initial'),
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension(),
    ]
