# Generated by Django 2.2.28 on 2025-03-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_django', '0002_auto_20250326_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='people_voted',
            field=models.IntegerField(default=0),
        ),
    ]
