# Generated by Django 2.2.28 on 2025-03-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_django', '0002_forum_locationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
