# Generated by Django 2.2.28 on 2025-03-28 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather_django', '0003_location_people_voted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='rating',
            new_name='total_rating',
        ),
        migrations.AlterField(
            model_name='forum',
            name='max_comments',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField()),
                ('date_rated', models.DateField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_django.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ratings',
                'unique_together': {('user', 'location', 'date_rated')},
            },
        ),
    ]
