# Generated by Django 2.2.28 on 2025-03-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_django', '0003_auto_20250317_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
