# Generated by Django 2.2.28 on 2025-03-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_django', '0004_auto_20250328_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='weather_description',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
