# Generated by Django 2.2.28 on 2025-03-25 21:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_django', '0005_auto_20250317_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default='Test', size=None),
            preserve_default=False,
        ),
    ]
